source 'https://rubygems.org'
ruby '2.2.3'

group :test do
  gem 'rspec'
  gem 'cucumber'
  gem 'rake'
  gem 'coveralls', require: false
  gem 'data_mapper'
  gem 'dm-postgres-adapter'
  gem 'bcrypt'
  gem 'database_cleaner'
  gem 'sinatra'
  gem 'sinatra-flash'
  gem 'capybara'
  gem 'rspec-sinatra'
  
end
